apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer
  selector:
    app: api-deployment
  ports:
    - port: 8301
      targetPort: 5452
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/agile-waterfall-inc/flooq-api:latest
          ports:
            - containerPort: 5452
          env:
            - name: DB_URL
              value: db
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: #TODO
            - name: DB_PASSWORD
              value: #TODO
            - name: API_TOKEN_EXECUTOR
              value: #TODO
            - name: API_TOKEN_EDITOR
              value: #TODO
