apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: LoadBalancer
  selector:
    app: db-deployment
  ports:
    - port: 3306
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      app: db-deployment
  # strategy: # TODO
  #   type: Recreate
  serviceName: db
  template:
    metadata:
      labels:
        app: db-deployment
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: db-deployment
          image: postgres
          imagePullPolicy: Always
          env: # TODO
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: flooqdatabase
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: csi-cinder-sc-retain
        resources:
          requests:
            storage: 1Gi
