apiVersion: apps/v1
kind: Deployment
metadata:
  name: editor-deployment
spec:
  selector:
    matchLabels:
      app: editor
  template:
    metadata:
      labels:
        app: editor
    spec:
      containers:
        - name: editor
          image: ghcr.io/agile-waterfall-inc/flooq-editor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: api
            - name: API_PORT
              value: "8301"
            - name: API_TOKEN
              value: asdf #TODO

