apiVersion: v1
kind: Service
metadata:
  name: executor
  labels:
    app: executor
spec:
  type: ClusterIP
  selector:
    app: executor
  ports:
    - name: web
      port: 3500
      targetPort: 3500
