apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: executor-monitor
  labels:
    k8s-app: executor-monitor
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: web
  selector:
    matchLabels:
      app: executor
  namespaceSelector:
    any: true
