apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor
  labels:
    app: executor
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: executor
  template:
    metadata:
      labels:
        app: executor
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: executor
          image: ghcr.io/agile-waterfall/flooq-executor:{{ .Values.version }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3500
          resources:
            limits:
              memory: "512M"
              cpu: "500m"
          env:
            - name: API_BASE_URL
              value: http://api:80
            - name: IDENTITY_SERVER_ISSUER
              value: {{ .Values.auth.identity.issuer }}
            - name: IDENTITY_SERVER_CLIENT_ID
              value: executor
            - name: IDENTITY_SERVER_CLIENT_SECRET
              value: {{ .Values.auth.identity.clientSecret }}

