apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flooq-ingress
spec:
  rules:
  - host: editor.staging.flooq.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: editor
            port:
              number: 3000
  - host: flooq-editor-{{ .Values.environment }}.k8s.init-lab.ch
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: editor
            port:
              number: 3000
  - host: flooq-editor-{{ .Values.environment }}.k8s.init-lab.ch
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: executor
            port:
              number: 3500