apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  labels:
    app: landing
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: landing
          image: ghcr.io/agile-waterfall-inc/flooq-landing:{{ .Values.version }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          resources:
            limits:
              memory: "512M"
              cpu: "500m"
          env:
            - name: API_BASE_URL
              value: http://api:80
            - name: NEXT_PUBLIC_EDITOR_URL
              value: http://localhost:3000
