kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv
  labels:
    type: local
spec:
  storageClassName: csi-cinder-sc-retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
