environment: prod
version: latest
env:
  ASPNETCORE_ENVIRONMENT: Production
services:
  database: flooq-prod-postgresql
postgresql:
  namespace: class-pm4-2022-5-prod
  storageClass: csi-cinder-sc-retain
  auth:
    username: flooqUser
    password: test1234 
    database: flooqdatabase
  primary:
    persistence:
      storageClass: csi-cinder-sc-retain
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi
  readReplicas:
    enabled: false
  metrics:
    enabled: false
  volumePersmissions:
    resources:
      limits:
        cpu: 100m
        memory: 200Mi