environment: staging
version: latest
env:
  ASPNETCORE_ENVIRONMENT: Development
services:
  database: flooq-staging-postgresql
auth:
  next:
    url: https://editor-staging.flooq.io
    issuer: https://identity-staging.flooq.io
postgresql:
  namespace: class-pm4-2022-5-staging
  storageClass: csi-cinder-sc-retain
  auth:
    username: flooqUser
    password: test1234
    database: flooqdatabase
    identityDatabase: flooqidentitydatabase
  primary:
    persistence:
      storageClass: csi-cinder-sc-retain
      size: 4Gi
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi
  readReplicas:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi
  metrics:
    enabled: false
  volumePersmissions:
    resources:
      limits:
        cpu: 100m
        memory: 200Mi