name: CD - Deploy Staging

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
          context: init-lab

      - uses: azure/k8s-bake@v2
        with:
          renderEngine: "helm"
          helmChart: "./.helm/"
          overrideFiles: './.helm/values-staging.yaml'
          helm-version: "latest"
          namespace: class-pm4-2022-5-staging
          releaseName: flooq-staging
        id: bake
      
      - name: Output Manifest
        run: cat ${{ steps.bake.outputs.manifestsBundle }}
        
      - uses: Azure/k8s-deploy@v1.4
        with:
          action: deploy
          namespace: class-pm4-2022-5-staging
          manifests: ${{ steps.bake.outputs.manifestsBundle }}    
          strategy: canary
          route-method: service
          version-switch-buffer: 1
          traffic-split-method: pod
          baseline-and-canary-replicas: 0
          force: true

      - uses: Azure/k8s-deploy@v1.4
        if: ${{ failure() }}
        with:
          action: reject
          namespace: class-pm4-2022-5-staging
          manifests: ${{ steps.bake.outputs.manifestsBundle }}

      - uses: Azure/k8s-deploy@v1.4
        with:
          action: promote
          namespace: class-pm4-2022-5-staging
          manifests: ${{ steps.bake.outputs.manifestsBundle }}