name: CI Build - Executor

on:
  workflow_dispatch:
    inputs:
  push:
    paths:
    - 'src/executor/**'
  pull_request:
    paths: 
    - 'src/executor/**'

defaults:
  run:
    shell: bash
    working-directory: src/executor/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 17.x
      uses: actions/setup-node@v2
      with:
        node-version: 17.x
        cache: 'npm'
        cache-dependency-path: src/executor/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --ci --passWithNoTestsst
