name: CI Build - Executor

on:
  workflow_dispatch:
    inputs:
  push:
    paths:
    - 'src/executor/**'
  pull_request:
    paths: 
    - 'src/executor/**'
  release:
    types: [published]

defaults:
  run:
    shell: bash
    working-directory: src/executor/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 17.x
      uses: actions/setup-node@v2
      with:
        node-version: 17.x
        cache: 'npm'
        cache-dependency-path: src/executor/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --ci --passWithNoTests
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: src/executor/
        args: >
          -Dsonar.sources=source/
          -Dsonar.tests=spec/
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: contains('refs/heads/main refs/tags/', github.ref) || github.event_name == 'release'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        if: github.event_name != 'release' || github.event.action != 'created'
        with:
          context: src/executor/
          push: true
          tags: |
            ghcr.io/agile-waterfall-inc/flooq-executor:latest
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        if: github.event_name == 'release' && github.event.action == 'created'
        with:
          context: src/executor/
          push: true
          tags: |
            ghcr.io/agile-waterfall-inc/flooq-executor:${{ github.event.release.tag_name }}
            ghcr.io/agile-waterfall-inc/flooq-executor:latest
            
