name: CI Build - Executor

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - '**'
    paths:
      - 'src/executor/**'
    tags-ignore:
      - v*
  pull_request:
    paths: 
    - 'src/executor/**'

defaults:
  run:
    shell: bash
    working-directory: src/executor/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 17.x
      uses: actions/setup-node@v2
      with:
        node-version: 17.x
        cache: 'npm'
        cache-dependency-path: src/executor/package-lock.json
    - run: npm ci
    - run: npm run lint
    - run: npm run build --if-present
    - run: npm test --ci --passWithNoTests
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: src/executor/
        args: >
          -Dsonar.sources=source/
          -Dsonar.coverage.exclusion=Index.ts,utils/logging/*.ts
          -Dsonar.tests=spec/
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
