name: CI Build - Editor

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - '**'
    paths:
      - 'src/editor/**'
    tags-ignore:
      - v*
  pull_request:
    paths: 
    - 'src/editor/**'

defaults:
  run:
    shell: bash
    working-directory: src/editor/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: src/editor/package-lock.json
    - run: npm ci
    - run: npm run lint
    - run: npm run build --if-present
    - run: npm test --ci --passWithNoTests

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: src/editor/
        args: >
          -Dsonar.sources=pages,components,helper
          -Dsonar.coverage.exclusion=components/*,pages/*
          -Dsonar.tests=spec/
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  storybook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      fetch-depth: 0
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: src/editor/package-lock.json

    - run: npm ci

    - run: npm run build-storybook --openssl-legacy-provider
      if: github.event_name != 'workflow_dispatch'

    - name: Publish to Chromatic
      if: github.event_name != 'workflow_dispatch'
      uses: chromaui/action@v1
      with:
        workingDir: src/editor/
        storybookBuildDir: src/editor/storybook-static
        exitZeroOnChanges: true
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
