name: CI Build - Editor

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - '**'
    paths:
      - 'src/editor/**'
    tags-ignore:
      - v*
  pull_request:
    paths: 
    - 'src/editor/**'

defaults:
  run:
    shell: bash
    working-directory: src/editor/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 17.x
      uses: actions/setup-node@v2
      with:
        node-version: 17.x
        cache: 'npm'
        cache-dependency-path: src/editor/package-lock.json
    - run: npm ci
    - run: npm run lint
    - run: npm run build --if-present
    - run: npm test --ci --passWithNoTests
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: src/editor/
        args: >
          -Dsonar.sources=pages,components,helper
          -Dsonar.coverage.exclusion=components/*,pages/*
          -Dsonar.tests=spec/
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - run: npm run build-storybook
    - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
