name: CI Build - Landing

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - '**'
    paths:
      - 'src/landing/**'
    tags-ignore:
      - v*
  pull_request:
    paths: 
    - 'src/landing/**'

defaults:
  run:
    shell: bash
    working-directory: src/landing/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 17.x
      uses: actions/setup-node@v2
      with:
        node-version: 17.x
        cache: 'npm'
        cache-dependency-path: src/landing/package-lock.json
    - run: npm ci
    - run: npm run lint
    - run: npm run build --if-present
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: src/landing/
        args: >
          -Dsonar.sources=pages,components,helper
          -Dsonar.coverage.exclusion=components/*,pages/*
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
